### PR TITLE
Add airline theme

### LINKED ISSUE #31: Add support for vim-airline again
After the changes in #21 (specifically edfed09), support for `vim-airline` was removed with the message:

> the current version is broken and I'm not using vim-airline at the moment

There's another closed issue (#26) that also brings this up, so I sent a PR (#30) to add it back but it's still broken. From the discussion in https://github.com/kaicataldo/material.vim/pull/30#issuecomment-535629963, I'm closing the PR and opening this issue to track this feature.

----

For now, I'm sticking to the old version to keep using it with `vim-airline`:

```vim
Plug 'kaicataldo/material.vim', {'commit': '5aabe47'}
```

### PR DESCRIPTION
**Pull request by gko**
reverted airline theme with a couple of modifications

# Palenight

## Normal
image

## Insert
image

## Visual
image

# Lighter

## Normal
image

## Insert
image

## Visual
image

# Darker

## Normal
image

## Insert

image

## Visual
image

# Ocean

## Normal
image

## Insert
image

## Visual
image

# Default

## Normal
image

## Insert
image

## Visual
image
 
closes #31

### CODE REVIEW

**Comment by kaicataldo** [comment]
Do you mind sharing a screenshot?

**Comment by gko** [comment]
> Do you mind sharing a screenshot?

done @kaicataldo

**Comment by kaicataldo** [comment]
Wow, thanks for the extensive screenshot gallery! I think this looks great.

One question I have: is it possible to use the global colors map so that the colors are centralized in one location (we do this in the [lightline theme](https://github.com/kaicataldo/material.vim/blob/46b6ca036b5238836e332a52d1f013cba8cc26b3/autoload/lightline/colorscheme/material_vim.vim#L6)). This would allow for the theme to stay consistent even we change the `highlight` definitions for syntax in the future.

**Comment by gko** [comment]
> One question I have: is it possible to use the global colors map so that the colors are centralized in one location (we do this in the [lightline theme](https://github.com/kaicataldo/material.vim/blob/46b6ca036b5238836e332a52d1f013cba8cc26b3/autoload/lightline/colorscheme/material_vim.vim#L6)). This would allow for the theme to stay consistent even we change the `highlight` definitions for syntax in the future.

@kaicataldo done

**Review by kaicataldo — APPROVED** [review]
Thank you! This LGTM.

**Pull request merged**
