### PR TITLE
Extend pangloss vim-javascript support

### PR DESCRIPTION
**Pull request by lmlorca**
This patch adds covers more syntax groups, from the vim-javascript plugin, making JavaScript files look more similar to the Material Theme. I include a comparison with some dummy js:

### Current JavaScript look in material.vim
material-vim-current

### How Material Theme looks
material-vscode

### With this addition, material.vim looks like the original
material-vim-new

The only thing we can't match right now is the special constructor highlight, and the class highlight when creating with the new keyword (vim-javascript-pangloss doesn't seem to have syntax groups for them and identifies as regular methods).

Comparison with light variant

### Current material.vim
material-light-vim-current

### With this patch
material-light-vim-new

### CODE REVIEW

**Comment by kaicataldo** [comment]
Hey, thanks for the PR! This theme is modeled after the original Material theme (I think it's called Material Community now?). I'm totally fine with adding support for the current modern Material theme, but I'd love to preserve the original as well. Maybe we can add some new variants? i.e. rename the current ones as `*-community` and then add the changes here in the standard named ones? This would be a "breaking change" in that it'll update everyone's themes by default, but I think that's okay since it'll have the original themes available as well.

**Comment by lmlorca** [comment]
I think its a good idea in the sense that a newer version should ideally be default, while a legacy version could also be offered (just like the official theme does). However this PR, and I think new language features, can't work with just variants (because variants only change the color values, they're agnostic to the changes in the syntax groups themselves). I think it would be easier to split the colorscheme file in two (the file inside colors/ folder). That way it would be easier to add new features, while keeping the community colorscheme "closed", like its "upstream" counter-part. Fixes in the legacy version could still be pushed into the community-material.vim file, and it could be selected by setting "community-material" as colorscheme in vimrc/init, while leaving the material.vim file open for new language features, etc. The names of the variants could also remain the same this way (colorscheme "community-material", with "darker", "default", "lighter", etc.). What do you think?

**Comment by kaicataldo** [comment]
Is it possible for a single color scheme plugin to export two different color schemes?

From a maintenance perspective, I want to share as much code as possible (until we hit a point where they're different enough that this becomes a burden). What if we start by conditionally setting the highlights based on the color scheme set?

I'm not against exploring your suggestion in the future. I just don't want to duplicate a bunch of stuff that we have to keep in sync.

**Comment by lmlorca** [comment]
I pushed a small change that sets the same color values for "darker" || "darker-community", etc... Then in the vim-javascript group, checked if the style doesn't match "-community$", to set the specific new syntax, else use the old one. Only done for vim-javascript, but I imagine eventually other syntax groups may also be split (the reason I didn't use an expression at the top when setting the color values, is to make the full theme variant names explicit somewhere in the code, but then use an expression to conditionally apply the syntax group if the variant actually ends or not in "-community").

**Comment by kaicataldo** [comment]
Thanks! This seems like a good incremental solution for the time being :+1:

**Comment by kaicataldo** [comment]
Do you mind updating the readme?

**Comment by lmlorca** [comment]
Done, I hope its clear! Tried not to over-extend it, because I like how concise and clear the readme is.

**Review by kaicataldo — APPROVED** [review]

**Comment by kaicataldo** [comment]
LGTM, thanks!

**Pull request merged**
