### PR TITLE
Syntax highlighting for Tex, LaTeX etc

### PR DESCRIPTION
**Pull request by ashwinvis**

### CODE REVIEW

**Comment by ashwinvis** [comment]
#### Before
before
#### After
after

**Comment by kaicataldo** [comment]
Hey, thanks for the PR! This definitely looks like an improvement and I'd love to merge this.

One question I have: is there a reason `\section{Test Section}` is highlighted differently than `\begin{}` and `\end{}`?

**Comment by ashwinvis** [comment]
That is consistent with how section, subsection etc are highlighted in other colorschemes such as solarized.

**Comment by ashwinvis** [comment]
You can see for yourself with the source file: https://github.com/jcanton/mechthesis/blob/802613f0d410973935646d1bfffd43c08b7fe298/paper2/article.tex#L365-L390

**Review by kaicataldo — APPROVED** [review]
Thanks for the PR! This LGTM.

**Pull request merged**
