### PR TITLE
Update deprecated treesitter highlight groups

### PR DESCRIPTION
**Pull request by cherryman**
See https://github.com/nvim-treesitter/nvim-treesitter/pull/3656.

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks for the contribution! Definitely want to add support for this. Is there a way to do it in a backwards-compatible way for Neovim < 0.8? I'm not against dropping support when we need to, but I'd like to avoid it if it's not too much work to retain support. Can we not just have this be additive for now (i.e. leave the existing highlight definitions and add these new ones below)? If we can, mind updating that and adding a comment in about how the old definitions can be removed when we drop support for Neovim@0.7?

**Comment by cherryman** [comment]
Are the changes good?

**Review by kaicataldo — APPROVED** [review]
LGTM, thanks!

**Comment by kaicataldo** [comment]
I'm going to revert this change because it's breaking the plugin for some users (see https://github.com/kaicataldo/material.vim/issues/70). Happy to revisit if you'd like to continue working on this!

**Pull request merged**
