### PR TITLE
Change HTML syntax to better match Material Theme

### PR DESCRIPTION
**Pull request by lmlorca**

### CODE REVIEW

**Comment by lmlorca** [comment]
It seems it also affects html tags in PHP, so this change should also improve the syntax of templating engines that share the same base html vim syntax groups.

**Comment by kaicataldo** [comment]
Mind adding a screenshot for posterity?

**Comment by lmlorca** [comment]
Sorry I posted the result in the issue I opened but not here.

Darker:

Before:


Now:


Ocean:

Before:


Now:


Lighter:

Before:


Now:


Palenight:

Before:


Now:


So basically it improves basic HTML support by making the tags and the attributes different. Also it follows closer the original theme as well.

**Comment by kaicataldo** [comment]
Oh no, I didn’t mean to close this pull request. So sorry about that. Do you mind reopening it?

**Pull request closed without merging**
