### PR TITLE
Change HTML syntax to better match Material Theme

### PR DESCRIPTION
**Pull request by lmlorca**
Im not sure if this is how you reopen a PR...
Edit: It seems I had to make a new PR, didn't see any option to reopen the old one. For future reference, I copy again the comparison screenshots.

Darker:

Before:

Now:

Ocean:

Before:

Now:

Lighter:

Before:

Now:

Palenight:

Before:

Now:

### CODE REVIEW

**Comment by kaicataldo** [comment]
Thanks! Sorry again for accidentally closing your PR!

**Review by kaicataldo — APPROVED** [review]

**Comment by kaicataldo** [comment]
LGTM, thank you!

**Comment by lmlorca** [comment]
Thank you for the fantastic theme. Best vim theme by far!

**Comment by kaicataldo** [comment]
Thanks for the kind words!

**Pull request merged**
